import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:formapp/customerVisitReport/bloc/bloc/customerVisitReport_bloc.dart';
import 'package:formapp/customerVisitReport/view/widget/coOrdinator.dart';
import 'package:formapp/customerVisitReport/view/widget/customernameWidget.dart';
import 'package:formapp/customerVisitReport/view/widget/tickFeilds.dart';
import 'package:formapp/main.dart';
import 'package:formapp/widgets/ktextFeild.dart';

import '../../widgets/KAutoText.dart';

class CustomerVisitReportCreate extends StatelessWidget {
  const CustomerVisitReportCreate({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        floatingActionButton: FloatingActionButton(
          backgroundColor: primaryColor,
          onPressed: () {
            context.read<CustomerVisitReportBloc>().add(SaveEvent());
            Navigator.of(context).pop();
          },
          child: const Icon(Icons.save),
        ),
        appBar: AppBar(
          elevation: 0,
          title: Text('Create Customer Details'),
          centerTitle: true,
        ),
        body: SingleChildScrollView(
            child: Padding(
          padding: const EdgeInsets.all(8.0),
          child: Container(
            decoration: BoxDecoration(
                borderRadius: BorderRadius.circular(5),
                border: Border.all(width: 2, color: Colors.grey)),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.end,
              children: [
                Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: SizedBox(
                    width: MediaQuery.of(context).size.width / 6,
                    child: Table(
                      border: TableBorder.all(
                          color: Colors.grey,
                          width: 1.5,
                          borderRadius: BorderRadius.circular(5)),
                      columnWidths: const {
                        0: FlexColumnWidth(5),
                        1: FlexColumnWidth(5),
                      },
                      children: [
                        TableRow(children: [
                          const Text(
                            "FT No.",
                            style: TextStyle(fontSize: 15.0),
                          ),
                          AutoGeneratedText(autoGeneratedValue: 1),
                        ]),
                        TableRow(children: [
                          const Text(
                            "Rev No.",
                            style: TextStyle(fontSize: 15.0),
                          ),
                          AutoGeneratedText(autoGeneratedValue: 25),
                        ]),
                        TableRow(children: [
                          const Text(
                            "Page No.",
                            style: TextStyle(fontSize: 15.0),
                          ),
                          AutoGeneratedText(autoGeneratedValue: 2),
                        ]),
                        TableRow(children: [
                          const Text(
                            "Date",
                            style: TextStyle(fontSize: 15.0),
                          ),
                          Text(
                            "${DateTime.now().day}/${DateTime.now().month}/${DateTime.now().year}",
                            style: const TextStyle(fontSize: 15.0),
                          ),
                        ]),
                      ],
                    ),
                  ),
                ),
                Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: Container(
                    padding: const EdgeInsets.all(8.0),
                    decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(5),
                        border: Border.all(width: 2, color: Colors.grey)),
                    alignment: Alignment.center,
                    width: MediaQuery.of(context).size.width,
                    child: Wrap(children: [
                      CustomerVisitReNmaeWidget(),CoordinatorFeild(),
                
                      EnquiryApprovalWidget(),
                      OrderAuditWidget(),
                      KTextField(
                        onChanged: (value) {
                          context.read<CustomerVisitReportBloc>().add(
                              CustomerVisitDetailsEvent(
                                  customerVisitDetails: value));
                        },
                        multiline: true,
                        initialText: '',
                        hintText: 'Customer Visit Details',
                      ),
                      KTextField(
                        onChanged: (value) {
                          context
                              .read<CustomerVisitReportBloc>()
                              .add(FeedbackEvent(feedback: value));
                        },
                        multiline: true,
                        initialText: '',
                        hintText: 'Feedback / Follow-up Details',
                      ),
                      KTextField(
                        onChanged: (value) {
                          context
                              .read<CustomerVisitReportBloc>()
                              .add(RemarksEvent(Remarks: value));
                        },
                        multiline: true,
                        initialText: '',
                        hintText: 'Remarks',
                      ),
                    ]),
                  ),
                ),
              ],
            ),
          ),
        )));
  }
}
