import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:formapp/enquiryReview/view/widgets/AmandmentReviewByName.dart';
import 'package:formapp/enquiryReview/view/widgets/QtyEn.dart';
import 'package:formapp/enquiryReview/view/widgets/ReviewedBy.dart';
import 'package:formapp/enquiryReview/view/widgets/amandmentEn.dart';
import 'package:formapp/enquiryReview/view/widgets/amandmentReviewdateEn.dart';
import 'package:formapp/enquiryReview/view/widgets/ammandmentdateEn.dart';
import 'package:formapp/enquiryReview/view/widgets/approvedBy.dart';
import 'package:formapp/enquiryReview/view/widgets/approveddateEn.dart';
import 'package:formapp/enquiryReview/view/widgets/approvelDateEn.dart';
import 'package:formapp/enquiryReview/view/widgets/approvelbyName.dart';
import 'package:formapp/enquiryReview/view/widgets/customernameWidget.dart';
import 'package:formapp/enquiryReview/view/widgets/enRecDate.dart';
import 'package:formapp/enquiryReview/view/widgets/enquiryDateEn.dart';
import 'package:formapp/enquiryReview/view/widgets/offerdueDateTime.dart';
import 'package:formapp/enquiryReview/view/widgets/productdescriptionEn.dart';
import 'package:formapp/enquiryReview/view/widgets/reviewedDateEn.dart';
import 'package:formapp/enquiryReview/view/widgets/termsEN.dart';
import 'package:formapp/main.dart';
import 'package:formapp/widgets/ktextFeild.dart';
import 'package:formapp/enquiryReview/bloc/bloc/enquiry_review_bloc.dart';

import '../../widgets/KAutoText.dart';

class CreateEnquiryReview extends StatelessWidget {
  const CreateEnquiryReview({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        floatingActionButton: FloatingActionButton(
          backgroundColor: primaryColor,
          onPressed: () {
            context.read<EnquiryReviewBloc>().add(SaveEvent());
            Navigator.of(context).pop();
          },
          child: const Icon(Icons.save),
        ),
        appBar: AppBar(
          elevation: 0,
          title: Text('Create Enquiry Review'),
          centerTitle: true,
        ),
        body: SingleChildScrollView(
            child: Padding(
          padding: const EdgeInsets.all(8.0),
          child: Container(
            decoration: BoxDecoration(
                borderRadius: BorderRadius.circular(5),
                border: Border.all(width: 2, color: Colors.grey)),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.end,
              children: [
                Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: SizedBox(
                    width: MediaQuery.of(context).size.width / 6,
                    child: Table(
                      border: TableBorder.all(
                          color: Colors.grey,
                          width: 1.5,
                          borderRadius: BorderRadius.circular(5)),
                      columnWidths: const {
                        0: FlexColumnWidth(5),
                        1: FlexColumnWidth(5),
                      },
                      children: [
                        TableRow(children: [
                          const Text(
                            "FT No.",
                            style: TextStyle(fontSize: 15.0),
                          ),
                          AutoGeneratedText(autoGeneratedValue: 1),
                        ]),
                        TableRow(children: [
                          const Text(
                            "Rev No.",
                            style: TextStyle(fontSize: 15.0),
                          ),
                          AutoGeneratedText(autoGeneratedValue: 25),
                        ]),
                        TableRow(children: [
                          const Text(
                            "Page No.",
                            style: TextStyle(fontSize: 15.0),
                          ),
                          AutoGeneratedText(autoGeneratedValue: 2),
                        ]),
                        TableRow(children: [
                          const Text(
                            "Date",
                            style: TextStyle(fontSize: 15.0),
                          ),
                          Text(
                            "${DateTime.now().day}/${DateTime.now().month}/${DateTime.now().year}",
                            style: const TextStyle(fontSize: 15.0),
                          ),
                        ]),
                      ],
                    ),
                  ),
                ),
                Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: Container(
                    padding: const EdgeInsets.all(8.0),
                    decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(5),
                        border: Border.all(width: 2, color: Colors.grey)),
                    alignment: Alignment.center,
                    width: MediaQuery.of(context).size.width,
                    child: Wrap(children: [
                      CustomerEQrReNmaeWidget(),
                      EnquiryRecDateWidget(),
                      KTextField(
                        onChanged: (value) {
                          context
                              .read<EnquiryReviewBloc>()
                              .add(EnquiryNOEvent(enquiry: value));
                        },
                        initialText: '',
                        hintText: 'Enquiry No',
                      ),
                      EnquiryEnDateWidget(),
                      ProductDescriptionWidgetEn(),
                      QtyWidgetEn(),
                      OfferDueTimeDateWidget(),
                      TermsandConditionsWidgetEn(),
                    ReviewedByName(),
                      ReviewedDateWidgetEn(),
                      ApprovelByName(),
                      ApprovelDateWidgetEn(),
                      AmandmentWidgetEn(),
                      AmmandmentdateWidgetEn(),
                      KTextField(
                        onChanged: (value) {
                          context
                              .read<EnquiryReviewBloc>()
                              .add(DetailsofAmandmentEvent(details: value));
                        },
                        initialText: '',
                        hintText: 'Details of Amandment',
                      ),
                      AmandmentReviewByName(),
                      AmmandmentReviewdateWidgetEn(),
                      ApproveddByName(),
                      ApprovedDateWidgetEn()
                    ]),
                  ),
                ),
              ],
            ),
          ),
        )));
  }
}
