import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:formapp/Issue&Return_Register/bloc/issue_and_return_register_bloc.dart';
import 'package:formapp/Issue&Return_Register/view/widgets/returnDate.dart';

import '../../main.dart';
import '../../widgets/KAutoDateSet.dart';
import '../../widgets/KNumberTextField.dart';
import '../../widgets/kautoGenerateTextField.dart';
import '../../widgets/ktextFeild.dart';
import 'widgets/issueDate.dart';

class CreateIssueCumReturnSlip extends StatelessWidget {
  const CreateIssueCumReturnSlip({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Create Issue Cum Return Slip'),
        centerTitle: true,
      ),
      floatingActionButton: FloatingActionButton(
        backgroundColor: primaryColor,
        onPressed: () {
          context.read<IssueAndReturnRegisterBloc>().add(SaveEvent());
        },
        child: const Icon(Icons.save),
      ),
      body: SingleChildScrollView(
        child: Container(
          alignment: Alignment.center,
          width: MediaQuery.of(context).size.width,
          child: Wrap(
            // alignment: WrapAlignment.spaceBetween,
            children: [
              KAutoGeneratedNumberTextField(
                nextNumber: 201,
                initialText: '',
                hintText: 'FT No.',
                onChanged: (value) {
                  context
                      .read<IssueAndReturnRegisterBloc>()
                      .add(FtNumberEvent(ftNumber: value));
                },
              ),
              KAutoGeneratedNumberTextField(
                nextNumber: 101,
                initialText: '',
                hintText: 'Rev No.',
                onChanged: (value) {
                  context
                      .read<IssueAndReturnRegisterBloc>()
                      .add(RevNumberEvent(revNumber: value));
                },
              ),
              KAutoGeneratedNumberTextField(
                nextNumber: 1,
                initialText: '',
                hintText: 'Page No.',
                onChanged: (value) {
                  context
                      .read<IssueAndReturnRegisterBloc>()
                      .add(PageNumberEvent(pageNumber: value));
                },
              ),
              const KAutoGeneratedDateTextField(
                label: Text('Date'),
              ),
              KNumberTextField(
                onChanged: (value) {
                  context
                      .read<IssueAndReturnRegisterBloc>()
                      .add(SlNumberEvent(slNumber: value));
                },
                initialText: '',
                hintText: 'Sl.No',
              ),
              KTextField(
                onChanged: (value) {
                  context.read<IssueAndReturnRegisterBloc>().add(
                      MaterialDescriotionEvent(materialDescriotion: value));
                },
                initialText: '',
                hintText: 'Material Description',
              ),
              const IssueDate(),
              KNumberTextField(
                onChanged: (value) {
                  int issueQty = int.tryParse(value) ?? 0;
                  context
                      .read<IssueAndReturnRegisterBloc>()
                      .add(IssueQtyEvent(issueQty: issueQty));
                },
                initialText: '',
                hintText: 'Issue Qty',
              ),
              KTextField(
                onChanged: (value) {
                  context
                      .read<IssueAndReturnRegisterBloc>()
                      .add(IssueToEvent(issueTo: value));
                },
                initialText: '',
                hintText: 'Issue To',
              ),
              const ReturnDate(),
              KNumberTextField(
                onChanged: (value) {
                  int returnQty = int.tryParse(value) ?? 0;

                  context
                      .read<IssueAndReturnRegisterBloc>()
                      .add(ReturnQtyEvent(returnQty: returnQty));
                },
                initialText: '',
                hintText: 'Return Qty',
              ),
              KTextField(
                onChanged: (value) {
                  context
                      .read<IssueAndReturnRegisterBloc>()
                      .add(ReturnByEvent(returnBy: value));
                },
                initialText: '',
                hintText: 'Return By',
              ),
              KTextField(
                onChanged: (value) {
                  context
                      .read<IssueAndReturnRegisterBloc>()
                      .add(RemarksEvent(remarks: value));
                },
                initialText: '',
                hintText: 'Remarks',
              ),
            ],
          ),
        ),
      ),
    );
  }
}
