import 'package:flutter/material.dart';

class KAutoGeneratedDateTextField extends StatefulWidget {
  const KAutoGeneratedDateTextField(
      {super.key, this.controller, this.onTap, required this.label});
  final TextEditingController? controller;
  final Function()? onTap;
  final Widget label;
  @override
  // ignore: library_private_types_in_public_api
  _KAutoGeneratedDateTextFieldState createState() =>
      _KAutoGeneratedDateTextFieldState();
}

class _KAutoGeneratedDateTextFieldState
    extends State<KAutoGeneratedDateTextField> {
  DateTime _currentDate = DateTime.now();
  final TextEditingController _controller = TextEditingController();

  @override
  void initState() {
    super.initState();
    _controller.text = _formatDate(_currentDate);
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(8.0),
      child: SizedBox(
        width: 400,
        child: TextField(
          controller: _controller,
          decoration: const InputDecoration(
            fillColor: Colors.white,
            hintText: 'Date',
            label: Text('Date'),
          ),
          onTap: () {
            setState(() {
              _currentDate = DateTime.now();
              _controller.text = _formatDate(_currentDate);
            });
          },
          readOnly: true,
          onSubmitted: (value) {
            // Save the value to your application's data store
          },
        ),
      ),
    );
  }

  String _formatDate(DateTime date) {
    return '${date.year}-${date.month.toString().padLeft(2, '0')}-${date.day.toString().padLeft(2, '0')}';
  }
}
