import 'package:flutter/material.dart';

class AutoGeneratedText extends StatefulWidget {
  AutoGeneratedText({super.key, required this.autoGeneratedValue});
  int autoGeneratedValue;
  // ignore: library_private_types_in_public_api
  _AutoGeneratedTextState createState() => _AutoGeneratedTextState();
}

class _AutoGeneratedTextState extends State<AutoGeneratedText> {
  @override
  void initState() {
    super.initState();
  }

  @override
  void dispose() {
    super.dispose();
    // Clean up any resources used by the widget
  }

  @override
  Widget build(BuildContext context) {
    widget.autoGeneratedValue++;
    return Text(
      widget.autoGeneratedValue.toString().padLeft(3, '0'),
      style: const TextStyle(fontSize: 15.0),
    );
  }
}
