import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:formapp/Daily_Stock_Statement/bloc/daily_stock_statement_bloc.dart';
import '../../main.dart';
import '../../widgets/KAutoDateSet.dart';
import '../../widgets/KNumberTextField.dart';
import '../../widgets/kautoGenerateTextField.dart';
import '../../widgets/ktextFeild.dart';
import 'widgets/stockDate.dart';

class CreateDailyStockStatement extends StatelessWidget {
  const CreateDailyStockStatement({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Create Daily Stock Statement'),
        centerTitle: true,
      ),
      floatingActionButton: FloatingActionButton(
        backgroundColor: primaryColor,
        onPressed: () {
          context.read<DailyStockStatementBloc>().add(SaveEvent());
        },
        child: const Icon(Icons.save),
      ),
      body: SingleChildScrollView(
        child: Container(
          alignment: Alignment.center,
          width: MediaQuery.of(context).size.width,
          child: Wrap(
            alignment: WrapAlignment.spaceBetween,
            children: [
              KAutoGeneratedNumberTextField(
                nextNumber: 201,
                initialText: '',
                hintText: 'FT No.',
                onChanged: (value) {
                  context
                      .read<DailyStockStatementBloc>()
                      .add(FtNumberEvent(ftNumber: value));
                },
              ),
              KAutoGeneratedNumberTextField(
                nextNumber: 101,
                initialText: '',
                hintText: 'Rev No.',
                onChanged: (value) {
                  context
                      .read<DailyStockStatementBloc>()
                      .add(RevNumberEvent(revNumber: value));
                },
              ),
              KAutoGeneratedNumberTextField(
                nextNumber: 1,
                initialText: '',
                hintText: 'Page No.',
                onChanged: (value) {
                  context
                      .read<DailyStockStatementBloc>()
                      .add(PageNumberEvent(pageNumber: value));
                },
              ),
              const KAutoGeneratedDateTextField(
                label: Text('Date'),
              ),
              KAutoGeneratedNumberTextField(
                nextNumber: 1,
                onChanged: (value) {
                  context
                      .read<DailyStockStatementBloc>()
                      .add(SlNumberEvent(slNumber: value));
                },
                initialText: '',
                hintText: 'Sl.No',
              ),
              const StockDate(),
              // const StockDate(),
              KTextField(
                onChanged: (value) {
                  context
                      .read<DailyStockStatementBloc>()
                      .add(DescriptionEvent(description: value));
                },
                initialText: '',
                hintText: 'Description',
              ),
              KNumberTextField(
                onChanged: (value) {
                  int openingStock = int.tryParse(value) ?? 0;
                  context
                      .read<DailyStockStatementBloc>()
                      .add(OpeningStockEvent(openingStock: openingStock));
                },
                initialText: '',
                hintText: 'Opening Stock',
              ),
              KNumberTextField(
                onChanged: (value) {
                  int purchase = int.tryParse(value) ?? 0;
                  context
                      .read<DailyStockStatementBloc>()
                      .add(PurchaseStockEvent(purchaseStock: purchase));
                },
                initialText: '',
                hintText: 'Purchase',
              ),
              KNumberTextField(
                onChanged: (value) {
                  int total = int.tryParse(value) ?? 0;
                  context
                      .read<DailyStockStatementBloc>()
                      .add(TotalStockEvent(totalStock: total));
                },
                initialText: '',
                hintText: 'Total',
              ),
              KNumberTextField(
                onChanged: (value) {
                  int issue = int.tryParse(value) ?? 0;
                  context
                      .read<DailyStockStatementBloc>()
                      .add(StockIssueEvent(stockIssue: issue));
                },
                initialText: '',
                hintText: 'Issue',
              ),
              KNumberTextField(
                onChanged: (value) {
                  int closingStock = int.tryParse(value) ?? 0;
                  context
                      .read<DailyStockStatementBloc>()
                      .add(ClosingStockEvent(closingStock: closingStock));
                },
                initialText: '',
                hintText: 'Closing Stock',
              ),
              KTextField(
                onChanged: (value) {
                  context
                      .read<DailyStockStatementBloc>()
                      .add(RemarksEvent(remarks: value));
                },
                initialText: '',
                hintText: 'Remarks',
              ),
            ],
          ),
        ),
      ),
    );
  }
}
