import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:formapp/Daily_Stock_Statement/bloc/daily_stock_statement_bloc.dart';
import '../../main.dart';
import '../../widgets/KAutoText.dart';
import '../../widgets/KNumberTextField.dart';
import '../../widgets/kautoGenerateTextField.dart';
import '../../widgets/ktextFeild.dart';
import 'widgets/description.dart';
import 'widgets/stockDate.dart';

class CreateDailyStockStatement extends StatelessWidget {
  const CreateDailyStockStatement({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Create Daily Stock Statement'),
        centerTitle: true,
      ),
      floatingActionButton: FloatingActionButton(
        backgroundColor: primaryColor,
        onPressed: () {
          context.read<DailyStockStatementBloc>().add(SaveEvent());
        },
        child: const Icon(Icons.save),
      ),
      body: SingleChildScrollView(
        child: Padding(
          padding: const EdgeInsets.all(8.0),
          child: Container(
            decoration: BoxDecoration(
                borderRadius: BorderRadius.circular(5),
                border: Border.all(width: 2, color: Colors.grey)),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.end,
              children: [
                Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: SizedBox(
                    width: MediaQuery.of(context).size.width / 6,
                    child: Table(
                      border: TableBorder.all(
                          color: Colors.grey,
                          width: 1.5,
                          borderRadius: BorderRadius.circular(5)),
                      columnWidths: const {
                        0: FlexColumnWidth(5),
                        1: FlexColumnWidth(5),
                      },
                      children: [
                        TableRow(children: [
                          const Text(
                            "FT No.",
                            style: TextStyle(fontSize: 15.0),
                          ),
                          AutoGeneratedText(autoGeneratedValue: 1),
                        ]),
                        TableRow(children: [
                          const Text(
                            "Rev No.",
                            style: TextStyle(fontSize: 15.0),
                          ),
                          AutoGeneratedText(autoGeneratedValue: 25),
                        ]),
                        TableRow(children: [
                          const Text(
                            "Page No.",
                            style: TextStyle(fontSize: 15.0),
                          ),
                          AutoGeneratedText(autoGeneratedValue: 2),
                        ]),
                        TableRow(children: [
                          const Text(
                            "Date",
                            style: TextStyle(fontSize: 15.0),
                          ),
                          Text(
                            "${DateTime.now().day}/${DateTime.now().month}/${DateTime.now().year}",
                            style: const TextStyle(fontSize: 15.0),
                          ),
                        ]),
                      ],
                    ),
                  ),
                ),
                Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: Container(
                    padding: const EdgeInsets.all(8),
                    decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(5),
                        border: Border.all(width: 2, color: Colors.grey)),
                    alignment: Alignment.center,
                    width: MediaQuery.of(context).size.width,
                    child: Wrap(
                      alignment: WrapAlignment.spaceBetween,
                      children: [
                        KAutoGeneratedNumberTextField(
                          nextNumber: 1,
                          onChanged: (value) {
                            context
                                .read<DailyStockStatementBloc>()
                                .add(SlNumberEvent(slNumber: value));
                          },
                          initialText: '',
                          hintText: 'Sl.No',
                        ),
                        const StockDate(),
                        const Description(),
                        KNumberTextField(
                          onChanged: (value) {
                            int openingStock = int.tryParse(value) ?? 0;
                            context.read<DailyStockStatementBloc>().add(
                                OpeningStockEvent(openingStock: openingStock));
                          },
                          initialText: '',
                          hintText: 'Opening Stock',
                        ),
                        KNumberTextField(
                          onChanged: (value) {
                            int purchase = int.tryParse(value) ?? 0;
                            context.read<DailyStockStatementBloc>().add(
                                PurchaseStockEvent(purchaseStock: purchase));
                          },
                          initialText: '',
                          hintText: 'Purchase',
                        ),
                        KNumberTextField(
                          onChanged: (value) {
                            int total = int.tryParse(value) ?? 0;
                            context
                                .read<DailyStockStatementBloc>()
                                .add(TotalStockEvent(totalStock: total));
                          },
                          initialText: '',
                          hintText: 'Total',
                        ),
                        KNumberTextField(
                          onChanged: (value) {
                            int issue = int.tryParse(value) ?? 0;
                            context
                                .read<DailyStockStatementBloc>()
                                .add(StockIssueEvent(stockIssue: issue));
                          },
                          initialText: '',
                          hintText: 'Issue',
                        ),
                        KNumberTextField(
                          onChanged: (value) {
                            int closingStock = int.tryParse(value) ?? 0;
                            context.read<DailyStockStatementBloc>().add(
                                ClosingStockEvent(closingStock: closingStock));
                          },
                          initialText: '',
                          hintText: 'Closing Stock',
                        ),
                        KTextField(
                          onChanged: (value) {
                            context
                                .read<DailyStockStatementBloc>()
                                .add(RemarksEvent(remarks: value));
                          },
                          initialText: '',
                          hintText: 'Remarks',
                        ),
                      ],
                    ),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
