import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:formapp/Gate_Inward_Register/bloc/gate_inward_register_bloc.dart';
import 'package:formapp/Gate_Inward_Register/view/widgets/checkedBy.dart';

import '../../main.dart';
import '../../widgets/KAutoDateSet.dart';
import '../../widgets/KAutoText.dart';
import '../../widgets/KNumberTextField.dart';
import '../../widgets/kautoGenerateTextField.dart';
import '../../widgets/ktextFeild.dart';
import 'widgets/gateInwardDateTime.dart';
import 'widgets/gateInwardDescription.dart';
import 'widgets/gatePassDate.dart';
import 'widgets/returnorNonReturnable.dart';

class CreateGateInwardRegister extends StatelessWidget {
  const CreateGateInwardRegister({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Create Gate Inward Register'),
        centerTitle: true,
      ),
      floatingActionButton: FloatingActionButton(
        backgroundColor: primaryColor,
        onPressed: () {
          context.read<GateInwardRegisterBloc>().add(SaveEvent());
        },
        child: const Icon(Icons.save),
      ),
      body: SingleChildScrollView(
        child: Padding(
          padding: const EdgeInsets.all(8.0),
          child: Container(
            decoration: BoxDecoration(
                borderRadius: BorderRadius.circular(5),
                border: Border.all(width: 2, color: Colors.grey)),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.end,
              children: [
                Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: SizedBox(
                    width: MediaQuery.of(context).size.width / 6,
                    child: Table(
                      border: TableBorder.all(
                          color: Colors.grey,
                          width: 1.5,
                          borderRadius: BorderRadius.circular(5)),
                      columnWidths: const {
                        0: FlexColumnWidth(5),
                        1: FlexColumnWidth(5),
                      },
                      children: [
                        TableRow(children: [
                          const Text(
                            "FT No.",
                            style: TextStyle(fontSize: 15.0),
                          ),
                          AutoGeneratedText(autoGeneratedValue: 1),
                        ]),
                        TableRow(children: [
                          const Text(
                            "Rev No.",
                            style: TextStyle(fontSize: 15.0),
                          ),
                          AutoGeneratedText(autoGeneratedValue: 25),
                        ]),
                        TableRow(children: [
                          const Text(
                            "Page No.",
                            style: TextStyle(fontSize: 15.0),
                          ),
                          AutoGeneratedText(autoGeneratedValue: 2),
                        ]),
                        TableRow(children: [
                          const Text(
                            "Date",
                            style: TextStyle(fontSize: 15.0),
                          ),
                          Text(
                            "${DateTime.now().day}/${DateTime.now().month}/${DateTime.now().year}",
                            style: const TextStyle(fontSize: 15.0),
                          ),
                        ]),
                      ],
                    ),
                  ),
                ),
                Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: Container(
                    padding: const EdgeInsets.all(8),
                    alignment: Alignment.center,
                    width: MediaQuery.of(context).size.width,
                    decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(5),
                        border: Border.all(width: 2, color: Colors.grey)),
                    child: Wrap(
                      alignment: WrapAlignment.spaceBetween,
                      children: [
                        KAutoGeneratedNumberTextField(
                          nextNumber: 1,
                          onChanged: (value) {
                            context.read<GateInwardRegisterBloc>().add(
                                GateInwardNumberEvent(gateInwardNumber: value));
                          },
                          initialText: '',
                          hintText: 'GI.No',
                        ),
                        const GateInwardDateTime(),
                        KAutoGeneratedNumberTextField(
                          nextNumber: 1,
                          onChanged: (value) {
                            context.read<GateInwardRegisterBloc>().add(
                                GatePassNumberEvent(gatePassNumber: value));
                          },
                          initialText: '',
                          hintText: 'GP.No',
                        ),
                        const GatePassDate(),
                        KTextField(
                          onChanged: (value) {
                            context
                                .read<GateInwardRegisterBloc>()
                                .add(FromEvent(from: value));
                          },
                          initialText: '',
                          hintText: 'From',
                        ),
                        KTextField(
                          onChanged: (value) {
                            context.read<GateInwardRegisterBloc>().add(
                                ModeOfTransportEvent(modeOfTransport: value));
                          },
                          initialText: '',
                          hintText: 'Mode Of Transport',
                        ),
                        KTextField(
                          onChanged: (value) {
                            context
                                .read<GateInwardRegisterBloc>()
                                .add(VehicleNumberEvent(vehicleNumber: value));
                          },
                          initialText: '',
                          hintText: 'Vehicle Number',
                        ),
                        const GateInwardDescription(),
                        KNumberTextField(
                          onChanged: (value) {
                            int quantity = int.tryParse(value) ?? 0;
                            context
                                .read<GateInwardRegisterBloc>()
                                .add(QuantityEvent(quantity: quantity));
                          },
                          initialText: '',
                          hintText: 'Quantity',
                        ),
                        KTextField(
                          onChanged: (value) {
                            context
                                .read<GateInwardRegisterBloc>()
                                .add(PurposeEvent(purpose: value));
                          },
                          initialText: '',
                          hintText: 'Purpose',
                        ),
                        const CheckedBy(),
                        // KTextField(
                        //   onChanged: (value) {
                        //     context
                        //         .read<GateInwardRegisterBloc>()
                        //         .add(CheckedByEvent(checkedBy: value));
                        //   },
                        //   initialText: '',
                        //   hintText: 'Checked By',
                        // ),
                        ReturnableOrNonReturnable(),
                        KTextField(
                          onChanged: (value) {
                            context
                                .read<GateInwardRegisterBloc>()
                                .add(RemarksEvent(remarks: value));
                          },
                          initialText: '',
                          hintText: 'Remarks',
                        ),
                      ],
                    ),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
