import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:formapp/Material_Required_Form/bloc/material_required_form_bloc.dart';
import 'package:formapp/Material_Required_Form/view/widgets/customerName.dart';
import 'package:formapp/Material_Required_Form/view/widgets/materialReqDescription.dart';
import 'package:formapp/Material_Required_Form/view/widgets/materialreqDate.dart';

import '../../main.dart';
import '../../widgets/KAutoText.dart';
import '../../widgets/kautoGenerateTextField.dart';
import '../../widgets/ktextFeild.dart';
import 'widgets/requisitionedBy.dart';

class CreateMaterialRequiredForm extends StatelessWidget {
  const CreateMaterialRequiredForm({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Create Material Required Form'),
        centerTitle: true,
      ),
      floatingActionButton: FloatingActionButton(
        backgroundColor: primaryColor,
        onPressed: () {
          context.read<MaterialRequiredFormBloc>().add(SaveEvent());
        },
        child: const Icon(Icons.save),
      ),
      body: SingleChildScrollView(
        child: Padding(
          padding: const EdgeInsets.all(8.0),
          child: Container(
            decoration: BoxDecoration(
                borderRadius: BorderRadius.circular(5),
                border: Border.all(width: 2, color: Colors.grey)),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.end,
              children: [
                Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: SizedBox(
                    width: MediaQuery.of(context).size.width / 6,
                    child: Table(
                      border: TableBorder.all(
                          color: Colors.grey,
                          width: 1.5,
                          borderRadius: BorderRadius.circular(5)),
                      columnWidths: const {
                        0: FlexColumnWidth(5),
                        1: FlexColumnWidth(5),
                      },
                      children: [
                        TableRow(children: [
                          const Text(
                            "FT No.",
                            style: TextStyle(fontSize: 15.0),
                          ),
                          AutoGeneratedText(autoGeneratedValue: 1),
                        ]),
                        TableRow(children: [
                          const Text(
                            "Rev No.",
                            style: TextStyle(fontSize: 15.0),
                          ),
                          AutoGeneratedText(autoGeneratedValue: 25),
                        ]),
                        TableRow(children: [
                          const Text(
                            "Page No.",
                            style: TextStyle(fontSize: 15.0),
                          ),
                          AutoGeneratedText(autoGeneratedValue: 2),
                        ]),
                        TableRow(children: [
                          const Text(
                            "Date",
                            style: TextStyle(fontSize: 15.0),
                          ),
                          Text(
                            "${DateTime.now().day}/${DateTime.now().month}/${DateTime.now().year}",
                            style: const TextStyle(fontSize: 15.0),
                          ),
                        ]),
                      ],
                    ),
                  ),
                ),
                Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: Container(
                    padding: const EdgeInsets.all(8.0),
                    decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(5),
                        border: Border.all(width: 2, color: Colors.grey)),
                    alignment: Alignment.center,
                    width: MediaQuery.of(context).size.width,
                    child: Wrap(
                      // alignment: WrapAlignment.spaceEvenly,
                      children: [
                        KAutoGeneratedNumberTextField(
                          nextNumber: 5,
                          initialText: '',
                          hintText: 'PO. No',
                        ),
                         KAutoGeneratedNumberTextField(
                          nextNumber: 1,
                          onChanged: (value) {
                            context
                                .read<MaterialRequiredFormBloc>()
                                .add(SlNumberEvent(slNumber: value));
                          },
                          initialText: '',
                          hintText: 'Sl.No',
                        ),
                        const CustomerName(),
                        // KTextField(
                        //   onChanged: (value) {
                        //     context
                        //         .read<MaterialRequiredFormBloc>()
                        //         .add(CustomerNameEvent(customerName: value));
                        //   },
                        //   initialText: '',
                        //   hintText: 'Customer Name',
                        // ),
                        const MaterialReqDate(),
                        const MaterialReqDescription(),
                        // KTextField(
                        //   onChanged: (value) {
                        //     context.read<MaterialRequiredFormBloc>().add(
                        //         MaterialDescriptionEvent(materialDescription: value));
                        //   },
                        //   initialText: '',
                        //   hintText: 'Material Description',
                        // ),
                        KTextField(
                          onChanged: (value) {
                            int inHand = int.tryParse(value) ?? 0;

                            context
                                .read<MaterialRequiredFormBloc>()
                                .add(InHandEvent(inHand: inHand));
                          },
                          initialText: '',
                          hintText: 'In Hand',
                        ),
                        KTextField(
                          onChanged: (value) {
                            int requiredQuantity = int.tryParse(value) ?? 0;

                            context.read<MaterialRequiredFormBloc>().add(
                                RequiredQuantityEvent(
                                    requiredQuantity: requiredQuantity));
                          },
                          initialText: '',
                          hintText: 'Req. Qty',
                        ),
                        KTextField(
                          onChanged: (value) {
                            int issuedQuantity = int.tryParse(value) ?? 0;

                            context.read<MaterialRequiredFormBloc>().add(
                                IssuedQuantityEvent(
                                    issuedQuantity: issuedQuantity));
                          },
                          initialText: '',
                          hintText: 'Issued Qty',
                        ),
                        KTextField(
                          onChanged: (value) {
                            context
                                .read<MaterialRequiredFormBloc>()
                                .add(RemarksEvent(remarks: value));
                          },
                          initialText: '',
                          hintText: 'Remarks',
                        ),
                        const RequisitionedBy(),
                        // KTextField(
                        //   onChanged: (value) {
                        //     context
                        //         .read<MaterialRequiredFormBloc>()
                        //         .add(RequisitionedByEvent(requisitionedBy: value));
                        //   },
                        //   initialText: '',
                        //   hintText: 'Requisitioned By',
                        // ),
                        KTextField(
                          onChanged: (value) {
                            context
                                .read<MaterialRequiredFormBloc>()
                                .add(SkSignEvent(skSign: value));
                          },
                          initialText: '',
                          hintText: 'Sk Sign',
                        ),
                        KTextField(
                          onChanged: (value) {
                            context
                                .read<MaterialRequiredFormBloc>()
                                .add(PeSignEvent(peSign: value));
                          },
                          initialText: '',
                          hintText: 'PE Sign',
                        ),
                      ],
                    ),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
