import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:formapp/Goods_Reciept_Note/bloc/goods_reciept_note_bloc.dart';
import 'package:formapp/Goods_Reciept_Note/view/widgets/GRNDescription.dart';
import 'package:formapp/Goods_Reciept_Note/view/widgets/billDate.dart';
import 'package:formapp/Goods_Reciept_Note/view/widgets/grnDate.dart';
import 'package:formapp/Goods_Reciept_Note/view/widgets/suppliername.dart';
import '../../main.dart';
import '../../widgets/KAutoText.dart';
import '../../widgets/KNumberTextField.dart';
import '../../widgets/kautoGenerateTextField.dart';
import '../../widgets/ktextFeild.dart';

class CreateGoodsRecieptNote extends StatelessWidget {
  const CreateGoodsRecieptNote({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Create Goods Reciept Note'),
        centerTitle: true,
      ),
      floatingActionButton: FloatingActionButton(
        backgroundColor: primaryColor,
        onPressed: () {
          context.read<GoodsRecieptNoteBloc>().add(SaveEvent());
        },
        child: const Icon(Icons.save),
      ),
      body: SingleChildScrollView(
        child: Padding(
          padding: const EdgeInsets.all(8.0),
          child: Container(
            decoration: BoxDecoration(
                borderRadius: BorderRadius.circular(5),
                border: Border.all(width: 2, color: Colors.grey)),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.end,
              children: [
                Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: SizedBox(
                    width: MediaQuery.of(context).size.width / 6,
                    child: Table(
                      border: TableBorder.all(
                          color: Colors.grey,
                          width: 1.5,
                          borderRadius: BorderRadius.circular(5)),
                      columnWidths: const {
                        0: FlexColumnWidth(5),
                        1: FlexColumnWidth(5),
                      },
                      children: [
                        TableRow(children: [
                          const Text(
                            "FT No.",
                            style: TextStyle(fontSize: 15.0),
                          ),
                          AutoGeneratedText(autoGeneratedValue: 1),
                        ]),
                        TableRow(children: [
                          const Text(
                            "Rev No.",
                            style: TextStyle(fontSize: 15.0),
                          ),
                          AutoGeneratedText(autoGeneratedValue: 25),
                        ]),
                        TableRow(children: [
                          const Text(
                            "Page No.",
                            style: TextStyle(fontSize: 15.0),
                          ),
                          AutoGeneratedText(autoGeneratedValue: 2),
                        ]),
                        TableRow(children: [
                          const Text(
                            "Date",
                            style: TextStyle(fontSize: 15.0),
                          ),
                          Text(
                            "${DateTime.now().day}/${DateTime.now().month}/${DateTime.now().year}",
                            style: const TextStyle(fontSize: 15.0),
                          ),
                        ]),
                      ],
                    ),
                  ),
                ),
                Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: Container(
                    padding: const EdgeInsets.all(8.0),
                    decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(5),
                        border: Border.all(width: 2, color: Colors.grey)),
                    alignment: Alignment.center,
                    width: MediaQuery.of(context).size.width,
                    child: Wrap(
                      // alignment: WrapAlignment.spaceBetween,
                      children: [
                        KNumberTextField(
                          onChanged: (value) {
                            context
                                .read<GoodsRecieptNoteBloc>()
                                .add(GrnNumberEvent(grnNumber: value));
                          },
                          initialText: '',
                          hintText: 'GRN.No',
                        ),
                        const GRNDate(),
                        SupplierName(),
                        // KTextField(
                        //   onChanged: (value) {
                        //     context
                        //         .read<GoodsRecieptNoteBloc>()
                        //         .add(SupplierNameEvent(supplierName: value));
                        //   },
                        //   initialText: '',
                        //   hintText: 'Supplier Name',
                        // ),
                        KNumberTextField(
                          onChanged: (value) {
                            context
                                .read<GoodsRecieptNoteBloc>()
                                .add(BillNumberEvent(billNumber: value));
                          },
                          initialText: '',
                          hintText: 'Bill No.',
                        ),
                        const BillDate(),
                        KAutoGeneratedNumberTextField(
                          nextNumber: 1,
                          onChanged: (value) {
                            context
                                .read<GoodsRecieptNoteBloc>()
                                .add(SlNumberEvent(slNumber: value));
                          },
                          initialText: '',
                          hintText: 'Sl.No',
                        ),
                        const GRNDescription(),
                        // KTextField(
                        //   onChanged: (value) {
                        //     context.read<GoodsRecieptNoteBloc>().add(
                        //         MaterialDescriotionEvent(materialDescriotion: value));
                        //   },
                        //   initialText: '',
                        //   hintText: 'Material Description',
                        // ),
                        KNumberTextField(
                          onChanged: (value) {
                            int orderQty = int.tryParse(value) ?? 0;
                            context
                                .read<GoodsRecieptNoteBloc>()
                                .add(OrderQtyEvent(orderQty: orderQty));
                          },
                          initialText: '',
                          hintText: 'Order Qty',
                        ),
                        KNumberTextField(
                          onChanged: (value) {
                            int acceptedQty = int.tryParse(value) ?? 0;
                            context.read<GoodsRecieptNoteBloc>().add(
                                RecievedQtyEvent(recievedQty: acceptedQty));
                          },
                          initialText: '',
                          hintText: 'Recieved Qty',
                        ),
                        KNumberTextField(
                          onChanged: (value) {
                            int acceptedQty = int.tryParse(value) ?? 0;
                            context.read<GoodsRecieptNoteBloc>().add(
                                AcceptedQtyEvent(acceptedQty: acceptedQty));
                          },
                          initialText: '',
                          hintText: 'Accepted Qty',
                        ),
                        KTextField(
                          onChanged: (value) {
                            context.read<GoodsRecieptNoteBloc>().add(
                                InspectionDetailsEvent(
                                    inspectionDetails: value));
                          },
                          initialText: '',
                          hintText: 'Inspection Details',
                        ),
                        KTextField(
                          onChanged: (value) {
                            context.read<GoodsRecieptNoteBloc>().add(
                                IFRejectionDetailsEvent(
                                    ifrejectionDetails: value));
                          },
                          initialText: '',
                          hintText: 'If Rejection Details',
                        ),
                        KTextField(
                          onChanged: (value) {
                            context
                                .read<GoodsRecieptNoteBloc>()
                                .add(RemarksEvent(remarks: value));
                          },
                          initialText: '',
                          hintText: 'Remarks',
                        ),
                      ],
                    ),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
